<?php 
/*
Plugin Name: WP Property for sale
Plugin URI: https://github.com/frahim/wp-property-for-sale
Description: WP Property for sale Plugin
Version: 1.0.0
Author: Md Yeasir Arafat
Author URI: https://github.com/frahim
Text Domain: wpfs
Generated By: http://ensuredomains.com
*/

// If this file is called directly, abort. //
if ( ! defined( 'WPINC' ) ) {die;} // end if

// Let's Initialize Everything
if ( file_exists( plugin_dir_path( __FILE__ ) . 'core-init.php' ) ) {
require_once( plugin_dir_path( __FILE__ ) . 'core-init.php' );
}